language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
env:
  - MONGOHQ_URL=mongodb://localhost:27017/jsonresume
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
before_script:
  - echo Give MongoDB time to start accepting connections
  - sleep 15
